// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logic

import (
	"github.com/google/wire"
	"go-tpl/infra"
	"go-tpl/logic/permission"
	"go-tpl/logic/role"
	"go-tpl/logic/user"
)

// Injectors from wire.go:

func initialize() *Service {
	db := infra.ProvideDB()
	client := infra.ProvideRedis()
	service := user.NewService(db, client)
	roleService := role.NewService(db)
	permissionService := permission.NewService(db)
	logicService := &Service{
		User:       service,
		Role:       roleService,
		Permission: permissionService,
	}
	return logicService
}

// wire.go:

type Service struct {
	User       *user.Service
	Role       *role.Service
	Permission *permission.Service
}

var providerSet = wire.NewSet(infra.ProvideDB, infra.ProvideRedis)

var svcSet = wire.NewSet(user.NewService, role.NewService, permission.NewService)
